name: id-token-debug

on:
  workflow_dispatch:

jobs:
  get-id-token:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Request OIDC Token
        run: |
          echo "Retrieving OIDC Token..."
          RESPONSE=$(curl -s -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL")
          echo "Raw Response: $RESPONSE"
          
          ID_TOKEN=$(echo "$RESPONSE" | jq -r .value)
          if [ -z "$ID_TOKEN" ] || [ "$ID_TOKEN" == "null" ]; then
            echo "❌ ERROR: No OIDC Token received!"
            exit 1
          fi
          
          echo "Decoded OIDC Token:"
          echo "$ID_TOKEN" | base64 --decode | jq '.'
